export const USER_LOGIN = 'USER_LOGIN';
export const USER_PASSWORD = 'USER_PASSWORD';
export const PLANNING_FETCH_START = 'PLANNING_FETCH_START';
export const TASKS_FETCH_START = 'TASKS_FETCH_START';
