export const AUTH_FETCH_LOGIN_START = 'AUTH_FETCH_LOGIN_START';
export const PLANNING_FETCH_START = 'PLANNING_FETCH_START';
export const TASKS_FETCH_START = 'TASKS_FETCH_START';
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS';
export const TASKS_FETCH_ERROR = 'TASKS_FETCH_ERROR';
export const TASKS_UPDATE_START = 'TASKS_UPDATE_TASK';
export const TASKS_UPDATE_SUCCESS = 'TASKS_UPDATE_TASK';
export const TASKS_UPDATE_ERROR = 'TASKS_UPDATE_TASK';
