export const USER_LOGIN = 'USER_LOGIN';
export const USER_PASSWORD = 'USER_PASSWORD';
export const PLANNING_FETCH_START = 'PLANNING_FETCH_START';
export const PLANNING_FETCH_SUCCESS = 'PLANNING_FETCH_SUCCESS';
export const PLANNING_FETCH_ERROR = 'PLANNING_FETCH_ERROR';
export const TASKS_FETCH_START = 'TASKS_FETCH_START';
